// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

public interface UserMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional string text = 3;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>optional string text = 3;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>optional string text = 3;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
