// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

public interface UserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional string emoji = 3;</code>
   * @return Whether the emoji field is set.
   */
  boolean hasEmoji();
  /**
   * <code>optional string emoji = 3;</code>
   * @return The emoji.
   */
  java.lang.String getEmoji();
  /**
   * <code>optional string emoji = 3;</code>
   * @return The bytes for emoji.
   */
  com.google.protobuf.ByteString
      getEmojiBytes();
}
